### PR TITLE
Make intl-tel-inputs from different sources coexist nicely

### PR DESCRIPTION
**Pull request by timbreitkreutz**
We have used this plugin in our pop-up form snippet and it can clash with other uses on the same page from the owners or other plugins.

This PR makes it so that upon instantiation the first time, the plug-in looks for other instances that have already claimed a global space, and iterates until it finds an available key in the `window` object.  As a bonus, it makes the code slightly more resilient to interruption/interference form nefarious actors.

## Notes

* For review, note that this commit includes the builds, so you can look at both the grunt inputs (lower in diff) and outputs (higher in diff)

## Alternatives

Here are some possible other ways to do this:

* Put the new globals inside the existing one into an array, rather than creating a new one for each instance of the plugin.
* Leave the existing wrappers alone and create a special one for re-entry (e.g. `intro-plugin.js`).

### CODE REVIEW

**Comment by timbreitkreutz** [comment]
Hi I've tested this (had to do a couple minor tweaks on the deployed code to avoid clobbering globals with production client.js code, but almost none)

Control sites:
* http://sbrew.com/iti1.html
* http://sbrew.com/itijq.html

New code:
* http://sbrew.com/diti1.html
* http://sbrew.com/ditijq.html

**Comment by timbreitkreutz** [comment]
After this has settled I'll put together a PR for the main repo.  If the owner likes this then I'll spend more time on specs and whatnot.

**Comment by timbreitkreutz** [comment]
See https://github.com/DripEmail/drip/pull/19158 for test on prod private of version from SHA 3cb37b0.

**Review by jachin — APPROVED** [review]
This looks good. I wonder if we should be offering to push these changes up stream?

It's too bad this is jquery, but since this is used in ClientJS we should cast as wide a compatibility net as possible, so this approach seems quite reasonable.

**Comment by timbreitkreutz** [comment]
> This looks good. I wonder if we should be offering to push these changes up stream?
> 
> It's too bad this is jquery, but since this is used in ClientJS we should cast as wide a compatibility net as possible, so this approach seems quite reasonable.

Yes the plan to present this as a PR to the maintainers after we prove it out a bit more. And it's actually not in jQuery any more -- that's just for legacy support :)

**Review by sbone — APPROVED** [review]

**Comment by timbreitkreutz** [comment]
https://github.com/jackocnr/intl-tel-input/pull/1168 has been opened.  Please feel free to suggest improvements.

**Pull request merged**
